<?php
    $Klienci = UsefullBase::GetKlienciAccessOddzial($this->Baza, $this->Uzytkownik);
    $Klienci = Usefull::PolaczDwieTablice(array(0 => ' -- Wybierz --'), $Klienci);
    $Klasy = UsefullBase::GetPrzewoznikClass($this->Baza);
    $PrzewoznicyArr = UsefullBase::GetPrzewoznicyWithClass($this->Baza);
    $Przewoznicy = Usefull::PolaczDwieTablice(array(0 => array('nazwa' => ' -- Wybierz -- ')), $PrzewoznicyArr);
    $Form = new FormularzSimple();
    $Form->FormStart("sea_order", "", "post");
    echo '<table class="formularz">'; 
        echo "<tr>\n";
            echo "<th>SHIPPER (załadowca)</th>\n";
            echo "<td>\n";
                $Form->PoleTextarea("Sea[shipper]", $Values['shipper'], "style='width: 400px; height: 40px;'");
                echo "<br /><br />";
                $Form->PoleSelect("Sea[id_klient_shipper]", $Klienci, $Values['id_klient_shipper']);
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>CONSIGNEE (odbiorca)</th>\n";
            echo "<td>\n";
                $Form->PoleTextarea("Sea[consignee]", $Values['consignee'], "style='width: 400px; height: 40px;'");
                echo "<br /><br />";
                $Form->PoleSelect("Sea[id_klient_consignee]", $Klienci, $Values['id_klient_consignee']);
            echo "</td>\n";
        echo "</tr>\n";
         echo "<tr>\n";
            echo "<th>AGENT (partner w POL)</th>\n";
            echo "<td>\n";
                $Form->PoleTextarea("Sea[agent]", $Values['agent'], "style='width: 400px; height: 40px;'");
                echo "<br /><br />";
                echo ("<select name=\"Sea[id_przewoznik_agent]\">");
                    foreach($Przewoznicy as $PID => $PDane){
                        echo("<option value='$PID'".($Values['id_przewoznik_agent'] == $PID ? ' selected="selected"' : '')."".($PDane['klasa_id'] > 0 ? " style='background-color: {$Klasy[$PDane['klasa_id']]['klasa_color']};'" : "").">{$PDane['nazwa']} ".($PID > 0 ? "({$Klasy[$PDane['klasa_id']]['klasa_nazwa']})" : "")."</option>");
                    }
		echo("</select>");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>NOTIFY ADDRESS</th>\n";
            echo "<td>\n";
                $Form->PoleTextarea("Sea[notify_adress]", $Values['notify_adress'], "style='width: 400px; height: 40px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>PLACE OF RECEIPT</th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[place_of_receipt]", $Values['place_of_receipt'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>VESSEL (statek)</th>\n";
            echo "<td>\n";
                $Form->PoleTextarea("Sea[vessel]", $Values['vessel'], "style='width: 400px; height: 40px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>POD (port rozładunku) </th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[pod]", $Values['pod'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>POL (port załadunku)</th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[pol]", $Values['pol'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>PLACE OF DELIVERY</th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[place_of_delivery]", $Values['place_of_delivery'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>Info przy specyfikacji</th>\n";
            echo "<td>\n";
                $Form->PoleTextarea("Sea[info]", $Values['info'], "style='width: 600px; height: 70px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>DECLARATION OF INTEREST</th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[declaration_of_interest]", $Values['declaration_of_interest'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>DECLARED VALUE</th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[declared_value]", $Values['declared_value'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>FREIGHT AMOUNT</th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[freight_amount]", $Values['freight_amount'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>FREIGHT PAYABLE AT</th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[freight_payable]", $Values['freight_payable'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>PLACE AND DATE OF ISSUE</th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[place_and_date_issue]", $Values['place_and_date_issue'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>NUMBER OF ORIGINAL FBL's</th>\n";
            echo "<td>\n";
                $Form->PoleInputText("Sea[number_fbl]", $Values['number_fbl'], "style='width: 200px;'");
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<th>ZAŁĄCZNIK w pliku</th>\n";
            echo "<td id='bl-attach'>\n";
                if(isset($Values['attachment']) && $Values['attachment'] != ""){
                    echo "<a href='BL-Attach/{$_GET['id']}-{$Values['attachment']}' target='_blank' />{$Values['attachment']}</a>\n";
                    echo "<br /><br />\n";
                    $Form->PoleButton("RemoveAtt", "Usuń plik", "onclick='RemoveAttach({$_GET['id']});'");
                }else{
                    $Form->PoleFile("Attach", "");
                }
            echo "</td>\n";
        echo "</tr>\n";
        echo "<tr>\n";
            echo "<td colspan='2' style='text-align: center;'>\n";
                $Form->PoleSubmitImage("OK", "Zapisz", "images/ok.gif", "style='border: 0;'");
                echo "&nbsp;&nbsp;";
                echo "<a href=\"$this->LinkPowrotu\"><img src=\"images/anuluj.gif\" border=\"0\"></a>";
            echo "</td>\n";
        echo "</tr>\n";
    $Form->FormEnd();
        echo '</table>'; 
?>